// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: article.proto

package me.binhct.middleware.proto;

public final class Article {
  private Article() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PArticleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PArticle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>repeated string oriKeywords = 2;</code>
     */
    java.util.List<java.lang.String>
        getOriKeywordsList();
    /**
     * <code>repeated string oriKeywords = 2;</code>
     */
    int getOriKeywordsCount();
    /**
     * <code>repeated string oriKeywords = 2;</code>
     */
    java.lang.String getOriKeywords(int index);
    /**
     * <code>repeated string oriKeywords = 2;</code>
     */
    com.google.protobuf.ByteString
        getOriKeywordsBytes(int index);

    /**
     * <code>string oriCategory = 3;</code>
     */
    java.lang.String getOriCategory();
    /**
     * <code>string oriCategory = 3;</code>
     */
    com.google.protobuf.ByteString
        getOriCategoryBytes();

    /**
     * <code>string oriUrl = 4;</code>
     */
    java.lang.String getOriUrl();
    /**
     * <code>string oriUrl = 4;</code>
     */
    com.google.protobuf.ByteString
        getOriUrlBytes();

    /**
     * <code>string publisher = 6;</code>
     */
    java.lang.String getPublisher();
    /**
     * <code>string publisher = 6;</code>
     */
    com.google.protobuf.ByteString
        getPublisherBytes();

    /**
     * <code>int64 timestamp = 7;</code>
     */
    long getTimestamp();

    /**
     * <code>repeated string paragraph = 8;</code>
     */
    java.util.List<java.lang.String>
        getParagraphList();
    /**
     * <code>repeated string paragraph = 8;</code>
     */
    int getParagraphCount();
    /**
     * <code>repeated string paragraph = 8;</code>
     */
    java.lang.String getParagraph(int index);
    /**
     * <code>repeated string paragraph = 8;</code>
     */
    com.google.protobuf.ByteString
        getParagraphBytes(int index);

    /**
     * <code>repeated string mediaUrl = 9;</code>
     */
    java.util.List<java.lang.String>
        getMediaUrlList();
    /**
     * <code>repeated string mediaUrl = 9;</code>
     */
    int getMediaUrlCount();
    /**
     * <code>repeated string mediaUrl = 9;</code>
     */
    java.lang.String getMediaUrl(int index);
    /**
     * <code>repeated string mediaUrl = 9;</code>
     */
    com.google.protobuf.ByteString
        getMediaUrlBytes(int index);

    /**
     * <code>string id = 10;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 10;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string description = 11;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 11;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string category = 12;</code>
     */
    java.lang.String getCategory();
    /**
     * <code>string category = 12;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();
  }
  /**
   * Protobuf type {@code PArticle}
   */
  public  static final class PArticle extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PArticle)
      PArticleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PArticle.newBuilder() to construct.
    private PArticle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PArticle() {
      title_ = "";
      oriKeywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      oriCategory_ = "";
      oriUrl_ = "";
      publisher_ = "";
      timestamp_ = 0L;
      paragraph_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      mediaUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      id_ = "";
      description_ = "";
      category_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PArticle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                oriKeywords_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              oriKeywords_.add(s);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              oriCategory_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              oriUrl_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              publisher_ = s;
              break;
            }
            case 56: {

              timestamp_ = input.readInt64();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                paragraph_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              paragraph_.add(s);
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                mediaUrl_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000080;
              }
              mediaUrl_.add(s);
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              category_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          oriKeywords_ = oriKeywords_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          paragraph_ = paragraph_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          mediaUrl_ = mediaUrl_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.binhct.middleware.proto.Article.internal_static_PArticle_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.binhct.middleware.proto.Article.internal_static_PArticle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.binhct.middleware.proto.Article.PArticle.class, me.binhct.middleware.proto.Article.PArticle.Builder.class);
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIKEYWORDS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList oriKeywords_;
    /**
     * <code>repeated string oriKeywords = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getOriKeywordsList() {
      return oriKeywords_;
    }
    /**
     * <code>repeated string oriKeywords = 2;</code>
     */
    public int getOriKeywordsCount() {
      return oriKeywords_.size();
    }
    /**
     * <code>repeated string oriKeywords = 2;</code>
     */
    public java.lang.String getOriKeywords(int index) {
      return oriKeywords_.get(index);
    }
    /**
     * <code>repeated string oriKeywords = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOriKeywordsBytes(int index) {
      return oriKeywords_.getByteString(index);
    }

    public static final int ORICATEGORY_FIELD_NUMBER = 3;
    private volatile java.lang.Object oriCategory_;
    /**
     * <code>string oriCategory = 3;</code>
     */
    public java.lang.String getOriCategory() {
      java.lang.Object ref = oriCategory_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oriCategory_ = s;
        return s;
      }
    }
    /**
     * <code>string oriCategory = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOriCategoryBytes() {
      java.lang.Object ref = oriCategory_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oriCategory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIURL_FIELD_NUMBER = 4;
    private volatile java.lang.Object oriUrl_;
    /**
     * <code>string oriUrl = 4;</code>
     */
    public java.lang.String getOriUrl() {
      java.lang.Object ref = oriUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oriUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string oriUrl = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOriUrlBytes() {
      java.lang.Object ref = oriUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oriUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBLISHER_FIELD_NUMBER = 6;
    private volatile java.lang.Object publisher_;
    /**
     * <code>string publisher = 6;</code>
     */
    public java.lang.String getPublisher() {
      java.lang.Object ref = publisher_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publisher_ = s;
        return s;
      }
    }
    /**
     * <code>string publisher = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPublisherBytes() {
      java.lang.Object ref = publisher_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publisher_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 7;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 7;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int PARAGRAPH_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList paragraph_;
    /**
     * <code>repeated string paragraph = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getParagraphList() {
      return paragraph_;
    }
    /**
     * <code>repeated string paragraph = 8;</code>
     */
    public int getParagraphCount() {
      return paragraph_.size();
    }
    /**
     * <code>repeated string paragraph = 8;</code>
     */
    public java.lang.String getParagraph(int index) {
      return paragraph_.get(index);
    }
    /**
     * <code>repeated string paragraph = 8;</code>
     */
    public com.google.protobuf.ByteString
        getParagraphBytes(int index) {
      return paragraph_.getByteString(index);
    }

    public static final int MEDIAURL_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList mediaUrl_;
    /**
     * <code>repeated string mediaUrl = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMediaUrlList() {
      return mediaUrl_;
    }
    /**
     * <code>repeated string mediaUrl = 9;</code>
     */
    public int getMediaUrlCount() {
      return mediaUrl_.size();
    }
    /**
     * <code>repeated string mediaUrl = 9;</code>
     */
    public java.lang.String getMediaUrl(int index) {
      return mediaUrl_.get(index);
    }
    /**
     * <code>repeated string mediaUrl = 9;</code>
     */
    public com.google.protobuf.ByteString
        getMediaUrlBytes(int index) {
      return mediaUrl_.getByteString(index);
    }

    public static final int ID_FIELD_NUMBER = 10;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 10;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 10;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 11;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 11;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORY_FIELD_NUMBER = 12;
    private volatile java.lang.Object category_;
    /**
     * <code>string category = 12;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      }
    }
    /**
     * <code>string category = 12;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      for (int i = 0; i < oriKeywords_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, oriKeywords_.getRaw(i));
      }
      if (!getOriCategoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, oriCategory_);
      }
      if (!getOriUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, oriUrl_);
      }
      if (!getPublisherBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, publisher_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(7, timestamp_);
      }
      for (int i = 0; i < paragraph_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, paragraph_.getRaw(i));
      }
      for (int i = 0; i < mediaUrl_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, mediaUrl_.getRaw(i));
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, id_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, description_);
      }
      if (!getCategoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, category_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < oriKeywords_.size(); i++) {
          dataSize += computeStringSizeNoTag(oriKeywords_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getOriKeywordsList().size();
      }
      if (!getOriCategoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, oriCategory_);
      }
      if (!getOriUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, oriUrl_);
      }
      if (!getPublisherBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, publisher_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, timestamp_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paragraph_.size(); i++) {
          dataSize += computeStringSizeNoTag(paragraph_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParagraphList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < mediaUrl_.size(); i++) {
          dataSize += computeStringSizeNoTag(mediaUrl_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMediaUrlList().size();
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, id_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, description_);
      }
      if (!getCategoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, category_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.binhct.middleware.proto.Article.PArticle)) {
        return super.equals(obj);
      }
      me.binhct.middleware.proto.Article.PArticle other = (me.binhct.middleware.proto.Article.PArticle) obj;

      boolean result = true;
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getOriKeywordsList()
          .equals(other.getOriKeywordsList());
      result = result && getOriCategory()
          .equals(other.getOriCategory());
      result = result && getOriUrl()
          .equals(other.getOriUrl());
      result = result && getPublisher()
          .equals(other.getPublisher());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getParagraphList()
          .equals(other.getParagraphList());
      result = result && getMediaUrlList()
          .equals(other.getMediaUrlList());
      result = result && getId()
          .equals(other.getId());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && getCategory()
          .equals(other.getCategory());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      if (getOriKeywordsCount() > 0) {
        hash = (37 * hash) + ORIKEYWORDS_FIELD_NUMBER;
        hash = (53 * hash) + getOriKeywordsList().hashCode();
      }
      hash = (37 * hash) + ORICATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getOriCategory().hashCode();
      hash = (37 * hash) + ORIURL_FIELD_NUMBER;
      hash = (53 * hash) + getOriUrl().hashCode();
      hash = (37 * hash) + PUBLISHER_FIELD_NUMBER;
      hash = (53 * hash) + getPublisher().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      if (getParagraphCount() > 0) {
        hash = (37 * hash) + PARAGRAPH_FIELD_NUMBER;
        hash = (53 * hash) + getParagraphList().hashCode();
      }
      if (getMediaUrlCount() > 0) {
        hash = (37 * hash) + MEDIAURL_FIELD_NUMBER;
        hash = (53 * hash) + getMediaUrlList().hashCode();
      }
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.binhct.middleware.proto.Article.PArticle parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.binhct.middleware.proto.Article.PArticle parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.binhct.middleware.proto.Article.PArticle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.binhct.middleware.proto.Article.PArticle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.binhct.middleware.proto.Article.PArticle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.binhct.middleware.proto.Article.PArticle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.binhct.middleware.proto.Article.PArticle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.binhct.middleware.proto.Article.PArticle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.binhct.middleware.proto.Article.PArticle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.binhct.middleware.proto.Article.PArticle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.binhct.middleware.proto.Article.PArticle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.binhct.middleware.proto.Article.PArticle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.binhct.middleware.proto.Article.PArticle prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PArticle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PArticle)
        me.binhct.middleware.proto.Article.PArticleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.binhct.middleware.proto.Article.internal_static_PArticle_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.binhct.middleware.proto.Article.internal_static_PArticle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.binhct.middleware.proto.Article.PArticle.class, me.binhct.middleware.proto.Article.PArticle.Builder.class);
      }

      // Construct using me.binhct.middleware.proto.Article.PArticle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        title_ = "";

        oriKeywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        oriCategory_ = "";

        oriUrl_ = "";

        publisher_ = "";

        timestamp_ = 0L;

        paragraph_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        mediaUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        id_ = "";

        description_ = "";

        category_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.binhct.middleware.proto.Article.internal_static_PArticle_descriptor;
      }

      public me.binhct.middleware.proto.Article.PArticle getDefaultInstanceForType() {
        return me.binhct.middleware.proto.Article.PArticle.getDefaultInstance();
      }

      public me.binhct.middleware.proto.Article.PArticle build() {
        me.binhct.middleware.proto.Article.PArticle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.binhct.middleware.proto.Article.PArticle buildPartial() {
        me.binhct.middleware.proto.Article.PArticle result = new me.binhct.middleware.proto.Article.PArticle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.title_ = title_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          oriKeywords_ = oriKeywords_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.oriKeywords_ = oriKeywords_;
        result.oriCategory_ = oriCategory_;
        result.oriUrl_ = oriUrl_;
        result.publisher_ = publisher_;
        result.timestamp_ = timestamp_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          paragraph_ = paragraph_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.paragraph_ = paragraph_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          mediaUrl_ = mediaUrl_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.mediaUrl_ = mediaUrl_;
        result.id_ = id_;
        result.description_ = description_;
        result.category_ = category_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.binhct.middleware.proto.Article.PArticle) {
          return mergeFrom((me.binhct.middleware.proto.Article.PArticle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.binhct.middleware.proto.Article.PArticle other) {
        if (other == me.binhct.middleware.proto.Article.PArticle.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.oriKeywords_.isEmpty()) {
          if (oriKeywords_.isEmpty()) {
            oriKeywords_ = other.oriKeywords_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureOriKeywordsIsMutable();
            oriKeywords_.addAll(other.oriKeywords_);
          }
          onChanged();
        }
        if (!other.getOriCategory().isEmpty()) {
          oriCategory_ = other.oriCategory_;
          onChanged();
        }
        if (!other.getOriUrl().isEmpty()) {
          oriUrl_ = other.oriUrl_;
          onChanged();
        }
        if (!other.getPublisher().isEmpty()) {
          publisher_ = other.publisher_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.paragraph_.isEmpty()) {
          if (paragraph_.isEmpty()) {
            paragraph_ = other.paragraph_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureParagraphIsMutable();
            paragraph_.addAll(other.paragraph_);
          }
          onChanged();
        }
        if (!other.mediaUrl_.isEmpty()) {
          if (mediaUrl_.isEmpty()) {
            mediaUrl_ = other.mediaUrl_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureMediaUrlIsMutable();
            mediaUrl_.addAll(other.mediaUrl_);
          }
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getCategory().isEmpty()) {
          category_ = other.category_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.binhct.middleware.proto.Article.PArticle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.binhct.middleware.proto.Article.PArticle) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 1;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList oriKeywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureOriKeywordsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          oriKeywords_ = new com.google.protobuf.LazyStringArrayList(oriKeywords_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string oriKeywords = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getOriKeywordsList() {
        return oriKeywords_.getUnmodifiableView();
      }
      /**
       * <code>repeated string oriKeywords = 2;</code>
       */
      public int getOriKeywordsCount() {
        return oriKeywords_.size();
      }
      /**
       * <code>repeated string oriKeywords = 2;</code>
       */
      public java.lang.String getOriKeywords(int index) {
        return oriKeywords_.get(index);
      }
      /**
       * <code>repeated string oriKeywords = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOriKeywordsBytes(int index) {
        return oriKeywords_.getByteString(index);
      }
      /**
       * <code>repeated string oriKeywords = 2;</code>
       */
      public Builder setOriKeywords(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOriKeywordsIsMutable();
        oriKeywords_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string oriKeywords = 2;</code>
       */
      public Builder addOriKeywords(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOriKeywordsIsMutable();
        oriKeywords_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string oriKeywords = 2;</code>
       */
      public Builder addAllOriKeywords(
          java.lang.Iterable<java.lang.String> values) {
        ensureOriKeywordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, oriKeywords_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string oriKeywords = 2;</code>
       */
      public Builder clearOriKeywords() {
        oriKeywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string oriKeywords = 2;</code>
       */
      public Builder addOriKeywordsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureOriKeywordsIsMutable();
        oriKeywords_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object oriCategory_ = "";
      /**
       * <code>string oriCategory = 3;</code>
       */
      public java.lang.String getOriCategory() {
        java.lang.Object ref = oriCategory_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oriCategory_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string oriCategory = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOriCategoryBytes() {
        java.lang.Object ref = oriCategory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oriCategory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string oriCategory = 3;</code>
       */
      public Builder setOriCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oriCategory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string oriCategory = 3;</code>
       */
      public Builder clearOriCategory() {
        
        oriCategory_ = getDefaultInstance().getOriCategory();
        onChanged();
        return this;
      }
      /**
       * <code>string oriCategory = 3;</code>
       */
      public Builder setOriCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oriCategory_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object oriUrl_ = "";
      /**
       * <code>string oriUrl = 4;</code>
       */
      public java.lang.String getOriUrl() {
        java.lang.Object ref = oriUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oriUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string oriUrl = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOriUrlBytes() {
        java.lang.Object ref = oriUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oriUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string oriUrl = 4;</code>
       */
      public Builder setOriUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oriUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string oriUrl = 4;</code>
       */
      public Builder clearOriUrl() {
        
        oriUrl_ = getDefaultInstance().getOriUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string oriUrl = 4;</code>
       */
      public Builder setOriUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oriUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object publisher_ = "";
      /**
       * <code>string publisher = 6;</code>
       */
      public java.lang.String getPublisher() {
        java.lang.Object ref = publisher_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          publisher_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string publisher = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPublisherBytes() {
        java.lang.Object ref = publisher_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publisher_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string publisher = 6;</code>
       */
      public Builder setPublisher(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publisher_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string publisher = 6;</code>
       */
      public Builder clearPublisher() {
        
        publisher_ = getDefaultInstance().getPublisher();
        onChanged();
        return this;
      }
      /**
       * <code>string publisher = 6;</code>
       */
      public Builder setPublisherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        publisher_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 7;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 7;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 7;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList paragraph_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParagraphIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          paragraph_ = new com.google.protobuf.LazyStringArrayList(paragraph_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string paragraph = 8;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getParagraphList() {
        return paragraph_.getUnmodifiableView();
      }
      /**
       * <code>repeated string paragraph = 8;</code>
       */
      public int getParagraphCount() {
        return paragraph_.size();
      }
      /**
       * <code>repeated string paragraph = 8;</code>
       */
      public java.lang.String getParagraph(int index) {
        return paragraph_.get(index);
      }
      /**
       * <code>repeated string paragraph = 8;</code>
       */
      public com.google.protobuf.ByteString
          getParagraphBytes(int index) {
        return paragraph_.getByteString(index);
      }
      /**
       * <code>repeated string paragraph = 8;</code>
       */
      public Builder setParagraph(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParagraphIsMutable();
        paragraph_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paragraph = 8;</code>
       */
      public Builder addParagraph(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParagraphIsMutable();
        paragraph_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paragraph = 8;</code>
       */
      public Builder addAllParagraph(
          java.lang.Iterable<java.lang.String> values) {
        ensureParagraphIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paragraph_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paragraph = 8;</code>
       */
      public Builder clearParagraph() {
        paragraph_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paragraph = 8;</code>
       */
      public Builder addParagraphBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureParagraphIsMutable();
        paragraph_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList mediaUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMediaUrlIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          mediaUrl_ = new com.google.protobuf.LazyStringArrayList(mediaUrl_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated string mediaUrl = 9;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMediaUrlList() {
        return mediaUrl_.getUnmodifiableView();
      }
      /**
       * <code>repeated string mediaUrl = 9;</code>
       */
      public int getMediaUrlCount() {
        return mediaUrl_.size();
      }
      /**
       * <code>repeated string mediaUrl = 9;</code>
       */
      public java.lang.String getMediaUrl(int index) {
        return mediaUrl_.get(index);
      }
      /**
       * <code>repeated string mediaUrl = 9;</code>
       */
      public com.google.protobuf.ByteString
          getMediaUrlBytes(int index) {
        return mediaUrl_.getByteString(index);
      }
      /**
       * <code>repeated string mediaUrl = 9;</code>
       */
      public Builder setMediaUrl(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMediaUrlIsMutable();
        mediaUrl_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mediaUrl = 9;</code>
       */
      public Builder addMediaUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMediaUrlIsMutable();
        mediaUrl_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mediaUrl = 9;</code>
       */
      public Builder addAllMediaUrl(
          java.lang.Iterable<java.lang.String> values) {
        ensureMediaUrlIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mediaUrl_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mediaUrl = 9;</code>
       */
      public Builder clearMediaUrl() {
        mediaUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mediaUrl = 9;</code>
       */
      public Builder addMediaUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMediaUrlIsMutable();
        mediaUrl_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 10;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 10;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 10;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 10;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 10;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 11;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 11;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 11;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 11;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 11;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object category_ = "";
      /**
       * <code>string category = 12;</code>
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          category_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string category = 12;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string category = 12;</code>
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string category = 12;</code>
       */
      public Builder clearCategory() {
        
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>string category = 12;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        category_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PArticle)
    }

    // @@protoc_insertion_point(class_scope:PArticle)
    private static final me.binhct.middleware.proto.Article.PArticle DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.binhct.middleware.proto.Article.PArticle();
    }

    public static me.binhct.middleware.proto.Article.PArticle getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PArticle>
        PARSER = new com.google.protobuf.AbstractParser<PArticle>() {
      public PArticle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PArticle(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PArticle> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PArticle> getParserForType() {
      return PARSER;
    }

    public me.binhct.middleware.proto.Article.PArticle getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PArticle_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PArticle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rarticle.proto\"\321\001\n\010PArticle\022\r\n\005title\030\001 " +
      "\001(\t\022\023\n\013oriKeywords\030\002 \003(\t\022\023\n\013oriCategory\030" +
      "\003 \001(\t\022\016\n\006oriUrl\030\004 \001(\t\022\021\n\tpublisher\030\006 \001(\t" +
      "\022\021\n\ttimestamp\030\007 \001(\003\022\021\n\tparagraph\030\010 \003(\t\022\020" +
      "\n\010mediaUrl\030\t \003(\t\022\n\n\002id\030\n \001(\t\022\023\n\013descript" +
      "ion\030\013 \001(\t\022\020\n\010category\030\014 \001(\tB\034\n\032me.binhct" +
      ".middleware.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PArticle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PArticle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PArticle_descriptor,
        new java.lang.String[] { "Title", "OriKeywords", "OriCategory", "OriUrl", "Publisher", "Timestamp", "Paragraph", "MediaUrl", "Id", "Description", "Category", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
