// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: goldprice.proto

package me.binhct.middleware.proto;

public final class Goldprice {
  private Goldprice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PGoldpriceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PGoldprice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string gType = 1;</code>
     */
    java.lang.String getGType();
    /**
     * <code>string gType = 1;</code>
     */
    com.google.protobuf.ByteString
        getGTypeBytes();

    /**
     * <code>int32 buy = 2;</code>
     */
    int getBuy();

    /**
     * <code>int32 sell = 3;</code>
     */
    int getSell();

    /**
     * <code>int64 timestamp = 4;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code PGoldprice}
   */
  public  static final class PGoldprice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PGoldprice)
      PGoldpriceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PGoldprice.newBuilder() to construct.
    private PGoldprice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PGoldprice() {
      gType_ = "";
      buy_ = 0;
      sell_ = 0;
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PGoldprice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              gType_ = s;
              break;
            }
            case 16: {

              buy_ = input.readInt32();
              break;
            }
            case 24: {

              sell_ = input.readInt32();
              break;
            }
            case 32: {

              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.binhct.middleware.proto.Goldprice.internal_static_PGoldprice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.binhct.middleware.proto.Goldprice.internal_static_PGoldprice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.binhct.middleware.proto.Goldprice.PGoldprice.class, me.binhct.middleware.proto.Goldprice.PGoldprice.Builder.class);
    }

    public static final int GTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object gType_;
    /**
     * <code>string gType = 1;</code>
     */
    public java.lang.String getGType() {
      java.lang.Object ref = gType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gType_ = s;
        return s;
      }
    }
    /**
     * <code>string gType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGTypeBytes() {
      java.lang.Object ref = gType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUY_FIELD_NUMBER = 2;
    private int buy_;
    /**
     * <code>int32 buy = 2;</code>
     */
    public int getBuy() {
      return buy_;
    }

    public static final int SELL_FIELD_NUMBER = 3;
    private int sell_;
    /**
     * <code>int32 sell = 3;</code>
     */
    public int getSell() {
      return sell_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, gType_);
      }
      if (buy_ != 0) {
        output.writeInt32(2, buy_);
      }
      if (sell_ != 0) {
        output.writeInt32(3, sell_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, gType_);
      }
      if (buy_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, buy_);
      }
      if (sell_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sell_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.binhct.middleware.proto.Goldprice.PGoldprice)) {
        return super.equals(obj);
      }
      me.binhct.middleware.proto.Goldprice.PGoldprice other = (me.binhct.middleware.proto.Goldprice.PGoldprice) obj;

      boolean result = true;
      result = result && getGType()
          .equals(other.getGType());
      result = result && (getBuy()
          == other.getBuy());
      result = result && (getSell()
          == other.getSell());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getGType().hashCode();
      hash = (37 * hash) + BUY_FIELD_NUMBER;
      hash = (53 * hash) + getBuy();
      hash = (37 * hash) + SELL_FIELD_NUMBER;
      hash = (53 * hash) + getSell();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.binhct.middleware.proto.Goldprice.PGoldprice parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.binhct.middleware.proto.Goldprice.PGoldprice parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.binhct.middleware.proto.Goldprice.PGoldprice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.binhct.middleware.proto.Goldprice.PGoldprice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.binhct.middleware.proto.Goldprice.PGoldprice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.binhct.middleware.proto.Goldprice.PGoldprice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.binhct.middleware.proto.Goldprice.PGoldprice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.binhct.middleware.proto.Goldprice.PGoldprice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.binhct.middleware.proto.Goldprice.PGoldprice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.binhct.middleware.proto.Goldprice.PGoldprice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.binhct.middleware.proto.Goldprice.PGoldprice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.binhct.middleware.proto.Goldprice.PGoldprice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.binhct.middleware.proto.Goldprice.PGoldprice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PGoldprice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PGoldprice)
        me.binhct.middleware.proto.Goldprice.PGoldpriceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.binhct.middleware.proto.Goldprice.internal_static_PGoldprice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.binhct.middleware.proto.Goldprice.internal_static_PGoldprice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.binhct.middleware.proto.Goldprice.PGoldprice.class, me.binhct.middleware.proto.Goldprice.PGoldprice.Builder.class);
      }

      // Construct using me.binhct.middleware.proto.Goldprice.PGoldprice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        gType_ = "";

        buy_ = 0;

        sell_ = 0;

        timestamp_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.binhct.middleware.proto.Goldprice.internal_static_PGoldprice_descriptor;
      }

      public me.binhct.middleware.proto.Goldprice.PGoldprice getDefaultInstanceForType() {
        return me.binhct.middleware.proto.Goldprice.PGoldprice.getDefaultInstance();
      }

      public me.binhct.middleware.proto.Goldprice.PGoldprice build() {
        me.binhct.middleware.proto.Goldprice.PGoldprice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.binhct.middleware.proto.Goldprice.PGoldprice buildPartial() {
        me.binhct.middleware.proto.Goldprice.PGoldprice result = new me.binhct.middleware.proto.Goldprice.PGoldprice(this);
        result.gType_ = gType_;
        result.buy_ = buy_;
        result.sell_ = sell_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.binhct.middleware.proto.Goldprice.PGoldprice) {
          return mergeFrom((me.binhct.middleware.proto.Goldprice.PGoldprice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.binhct.middleware.proto.Goldprice.PGoldprice other) {
        if (other == me.binhct.middleware.proto.Goldprice.PGoldprice.getDefaultInstance()) return this;
        if (!other.getGType().isEmpty()) {
          gType_ = other.gType_;
          onChanged();
        }
        if (other.getBuy() != 0) {
          setBuy(other.getBuy());
        }
        if (other.getSell() != 0) {
          setSell(other.getSell());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.binhct.middleware.proto.Goldprice.PGoldprice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.binhct.middleware.proto.Goldprice.PGoldprice) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object gType_ = "";
      /**
       * <code>string gType = 1;</code>
       */
      public java.lang.String getGType() {
        java.lang.Object ref = gType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGTypeBytes() {
        java.lang.Object ref = gType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gType = 1;</code>
       */
      public Builder setGType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gType = 1;</code>
       */
      public Builder clearGType() {
        
        gType_ = getDefaultInstance().getGType();
        onChanged();
        return this;
      }
      /**
       * <code>string gType = 1;</code>
       */
      public Builder setGTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gType_ = value;
        onChanged();
        return this;
      }

      private int buy_ ;
      /**
       * <code>int32 buy = 2;</code>
       */
      public int getBuy() {
        return buy_;
      }
      /**
       * <code>int32 buy = 2;</code>
       */
      public Builder setBuy(int value) {
        
        buy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 buy = 2;</code>
       */
      public Builder clearBuy() {
        
        buy_ = 0;
        onChanged();
        return this;
      }

      private int sell_ ;
      /**
       * <code>int32 sell = 3;</code>
       */
      public int getSell() {
        return sell_;
      }
      /**
       * <code>int32 sell = 3;</code>
       */
      public Builder setSell(int value) {
        
        sell_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sell = 3;</code>
       */
      public Builder clearSell() {
        
        sell_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PGoldprice)
    }

    // @@protoc_insertion_point(class_scope:PGoldprice)
    private static final me.binhct.middleware.proto.Goldprice.PGoldprice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.binhct.middleware.proto.Goldprice.PGoldprice();
    }

    public static me.binhct.middleware.proto.Goldprice.PGoldprice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PGoldprice>
        PARSER = new com.google.protobuf.AbstractParser<PGoldprice>() {
      public PGoldprice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PGoldprice(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PGoldprice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PGoldprice> getParserForType() {
      return PARSER;
    }

    public me.binhct.middleware.proto.Goldprice.PGoldprice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PGoldprice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PGoldprice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017goldprice.proto\"I\n\nPGoldprice\022\r\n\005gType" +
      "\030\001 \001(\t\022\013\n\003buy\030\002 \001(\005\022\014\n\004sell\030\003 \001(\005\022\021\n\ttim" +
      "estamp\030\004 \001(\003B\034\n\032me.binhct.middleware.pro" +
      "tob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PGoldprice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PGoldprice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PGoldprice_descriptor,
        new java.lang.String[] { "GType", "Buy", "Sell", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
